package dev.xylonity.bonsai.robots.client.entity.renderer;

import com.mojang.blaze3d.vertex.PoseStack;
import dev.xylonity.bonsai.robots.client.entity.layer.GenericMechPaletteLayer;
import dev.xylonity.bonsai.robots.common.entity.AbstractMechEntity;
import dev.xylonity.knightlib.api.util.KnightLibMath;
import dev.xylonity.knightlib.client.animation.model.KnightLibModel;
import dev.xylonity.knightlib.client.animation.renderer.KnightLibMobRenderer;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.phys.Vec3;
import net.minecraft.world.phys.shapes.VoxelShape;
import org.jetbrains.annotations.Nullable;

/**
 * IKs implementation based off ozz animation cpp lib
 * https://github.com/guillaumeblanc/ozz-animation/blob/master/samples/foot_ik/sample_foot_ik.cc
 * https://github.com/needle-mirror/com.unity.animation.rigging/blob/master/Runtime/Utils/AnimationRuntimeUtils.cs
 */
public abstract class AbstractMechRenderer<T extends AbstractMechEntity> extends KnightLibMobRenderer<T> {

    public static final String TORSO_BONE = "body_player_control";

    public static final String ROOT_BONE = "main";
    public static final String RIGHT_UPPER_LEG_BONE = "right_leg";
    public static final String RIGHT_LOWER_LEG_BONE = "right_leg_2";
    public static final String LEFT_UPPER_LEG_BONE = "left_leg";
    public static final String LEFT_LOWER_LEG_BONE = "left_leg_2";

    protected float torsoYawHalfLife = 1.5f;
    protected float legsYawHalfLife = 4.0f;
    protected float legIkHalfLife = 1.2f;

    // Minimal distance considered as movement
    protected double moveThresholdSqr = 1.0E-5;

    // Horizontal distance from the entity center to each foot column (in blocks)
    protected float footLateralOffset = 0.556f;

    protected float groundSearchUp = 0.8f;
    protected float groundSearchDown = 1.25f;

    public AbstractMechRenderer(EntityRendererProvider.Context context, float shadowRadius) {
        super(context, shadowRadius);
        addRenderLayer(new GenericMechPaletteLayer<>(this::getPaletteSprite));
    }

    /**
     * Sprite generated by the mech palette permutation
     */
    @Nullable
    protected ResourceLocation getPaletteSprite(T entity) {
        return null;
    }

    /**
     * Palette-enabled mechs draw their base model through {@link GenericMechPaletteLayer}
     */
    @Override
    protected RenderType getRenderType(T entity, boolean bodyVisible, boolean translucent, boolean glowing) {
        return getPaletteSprite(entity) == null ? super.getRenderType(entity, bodyVisible, translucent, glowing) : null;
    }

    /**
     * Prevents the death rotation
     */
    @Override
    protected float getFlipDegrees(T entity) {
        return 0.0F;
    }

    @Override
    protected void actuallyRender(T entity, float entityYaw, float partialTick, PoseStack poseStack, MultiBufferSource buffers, int packedLight, int renderColor) {
        if (entity.deathTime <= 0) {
            super.actuallyRender(entity, entityYaw, partialTick, poseStack, buffers, packedLight, renderColor);
            return;
        }

        final int deathTime = entity.deathTime;
        final int hurtTime = entity.hurtTime;
        entity.deathTime = 0;
        entity.hurtTime = 0;
        try {
            super.actuallyRender(entity, entityYaw, partialTick, poseStack, buffers, packedLight, renderColor);
        }
        finally {
            entity.deathTime = deathTime;
            entity.hurtTime = hurtTime;
        }

    }

    /**
     * The yaw state has to be refreshed before the model pose and the body rotation are evaluated, else both read the values of the previous frame
     */
    @Override
    protected void beforeRender(T entity, float entityYaw, float partialTick, PoseStack poseStack, MultiBufferSource buffers, int packedLight) {
        updatedPlayerControlledBoneYaw(entity, partialTick);
        if (supportsLegIk()) {
            updateLegIkState(entity, partialTick);
        }

    }

    /**
     * The whole model faces where the mech walks
     */
    @Override
    protected void setupRotations(T entity, PoseStack poseStack, float ageInTicks, float rotationYaw, float partialTick) {
        if (entity.clientYawInitialized) {
            rotationYaw = entity.clientLegsYaw;
        }

        super.setupRotations(entity, poseStack, ageInTicks, rotationYaw, partialTick);
    }

    /**
     * Counter rotates the torso back towards the camera, so it turns independently of the legs
     */
    @Override
    protected void setupPose(T entity, KnightLibModel model, float partialTick) {
        if (entity.clientYawInitialized && model.hasBone(TORSO_BONE)) {
            model.applyRotation(TORSO_BONE, 0f, KnightLibMath.angleDelta(entity.clientLegsYaw, entity.clientTorsoYaw), 0f);
        }

        applyLegIk(entity, model);
    }

    /**
     * Whether this renderer has leg IKs
     */
    protected boolean supportsLegIk() {
        return false;
    }

    /**
     * Implemented only by renderers whose leg rigs have IKs
     */
    protected void applyLegIk(T entity, KnightLibModel model) {
        ;;
    }

    protected boolean hasLegIkBones(KnightLibModel model) {
        return model.hasBone(ROOT_BONE)
                && model.hasBone(RIGHT_UPPER_LEG_BONE) && model.hasBone(RIGHT_LOWER_LEG_BONE)
                && model.hasBone(LEFT_UPPER_LEG_BONE) && model.hasBone(LEFT_LOWER_LEG_BONE);
    }

    /**
     * Lowers the body enough that the higher foot never needs to compress farther than its rig allows
     */
    protected float legIkBodySink(float leftGroundDelta, float rightGroundDelta, float maxLiftBlocks) {
        final float lowest = Math.min(leftGroundDelta, rightGroundDelta);
        final float highest = Math.max(leftGroundDelta, rightGroundDelta);
        return Mth.clamp(Math.max(lowest, highest - maxLiftBlocks), -maxLiftBlocks, 0f);
    }

    protected void updateLegIkState(T mech, float partialTick) {
        final float yaw = mech.clientYawInitialized ? mech.clientLegsYaw : Mth.rotLerp(partialTick, mech.yBodyRotO, mech.yBodyRot);
        final Vec3 lateral = new Vec3(footLateralOffset, 0.0D, 0.0D).yRot((float) Math.toRadians(-yaw));

        float leftTarget = 0f;
        float rightTarget = 0f;
        if (mech.onGround()) {
            leftTarget = groundDeltaAt(mech, mech.getX() + lateral.x, mech.getZ() + lateral.z);
            rightTarget = groundDeltaAt(mech, mech.getX() - lateral.x, mech.getZ() - lateral.z);
        }

        if (!mech.clientLegIkInitialized) {
            mech.clientLeftLegGroundDelta = leftTarget;
            mech.clientRightLegGroundDelta = rightTarget;
            mech.clientLegIkInitialized = true;
            return;
        }

        final Minecraft minecraft = Minecraft.getInstance();
        if (minecraft.isPaused()) {
            return;
        }

        final float alpha = smoothFactor(minecraft.getDeltaFrameTime(), legIkHalfLife);
        mech.clientLeftLegGroundDelta = Mth.lerp(alpha, mech.clientLeftLegGroundDelta, leftTarget);
        mech.clientRightLegGroundDelta = Mth.lerp(alpha, mech.clientRightLegGroundDelta, rightTarget);
    }

    /**
     * Height of the first collision surface under the given column relative to the entity position (in blocks)
     */
    protected float groundDeltaAt(T mech, double x, double z) {
        final double baseY = mech.getY();
        final BlockPos.MutableBlockPos blockPos = new BlockPos.MutableBlockPos();
        final int blockX = Mth.floor(x);
        final int blockZ = Mth.floor(z);

        for (int blockY = Mth.floor(baseY + groundSearchUp); blockY >= Mth.floor(baseY - groundSearchDown); blockY--) {
            blockPos.set(blockX, blockY, blockZ);
            final VoxelShape shape = mech.level().getBlockState(blockPos).getCollisionShape(mech.level(), blockPos);
            if (shape.isEmpty()) {
                continue;
            }

            final double top = blockY + shape.max(Direction.Axis.Y);
            if (top <= baseY + groundSearchUp) {
                return (float) Mth.clamp(top - baseY, -groundSearchDown, groundSearchUp);
            }

        }

        return -groundSearchDown;
    }

    protected void updatedPlayerControlledBoneYaw(T mech, float partialTick) {
        final Player player = mech.getPilot();
        if (player == null) {
            return;
        }

        // The torso follows the camera yaw
        final float lookYaw = player.getViewYRot(partialTick);
        if (!mech.clientYawInitialized) {
            mech.clientLegsYaw = lookYaw;
            mech.clientTorsoYaw = lookYaw;
            mech.clientLegsReversed = false;
            mech.clientYawInitialized = true;
            return;
        }

        final Minecraft minecraft = Minecraft.getInstance();
        if (minecraft.isPaused()) {
            return;
        }

        final float frameTicks = minecraft.getDeltaFrameTime();
        mech.clientTorsoYaw = KnightLibMath.lerpAngle(mech.clientTorsoYaw, lookYaw, smoothFactor(frameTicks, torsoYawHalfLife));

        final double dx = mech.getX() - mech.xo;
        final double dz = mech.getZ() - mech.zo;
        if (dx * dx + dz * dz > moveThresholdSqr) {
            final float moveYaw = KnightLibMath.yawAngleOf(new Vec3(dx, 0.0D, dz));

            // Rotates the legs to the front if they are reversed and realigns them anyway
            if (Math.abs(KnightLibMath.angleDelta(lookYaw, moveYaw)) < 80.0F) {
                mech.clientLegsReversed = false;
            }
            else {
                // Inverse leg directional rotation
                final float delta = Math.abs(KnightLibMath.angleDelta(mech.clientLegsYaw, moveYaw));
                if (mech.clientLegsReversed ? delta < 75.0F : delta > 105.0F) {
                    mech.clientLegsReversed = !mech.clientLegsReversed;
                }

            }

            final float targetYaw = mech.clientLegsReversed ? moveYaw + 180.0F : moveYaw;
            mech.clientLegsYaw = KnightLibMath.lerpAngle(mech.clientLegsYaw, targetYaw, smoothFactor(frameTicks, legsYawHalfLife));
        }

    }

    private static float smoothFactor(float frameTicks, float halfLifeTicks) {
        return 1.0f - (float) Math.pow(0.5, frameTicks / halfLifeTicks);
    }

}